### ISSUE TITLE
Error on prediction

### ISSUE THREAD

**Issue by sajanbhagat** [ParikhKadam/bidaf-keras#18]
I'm getting following error on training and predict call from terminal 

Python 3.6.8

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/bidaf/__main__.py", line 122, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/bidaf/__main__.py", line 85, in main
    bidaf_model.load_bidaf(os.path.join(os.path.dirname(__file__), 'saved_items', args.model_name))
  File "/usr/local/lib/python3.6/dist-packages/bidaf/models/bidaf.py", line 87, in load_bidaf
    self.model = load_model(path, custom_objects=custom_objects)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 584, in load_model
    model = _deserialize_model(h5dict, custom_objects, compile)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 333, in _deserialize_model
    str(len(weight_values)) +
TypeError: must be str, not bytes

**Comment by patilgirish815** [comment]
Facing the same Issue
TypeError: must be str, not bytes

**Comment by pg815** [comment]
Have you found any solution for this issue ?

**Comment by sajanbhagat** [comment]
No, i haven't found any solution yet

**Comment by ParikhKadam** [comment]
That's an environment error. Install tensorflow and keras versions mentioned in the requirements.txt file and this issue will be solved.
