### ISSUE TITLE
Errors when theano backened is running in Linux

### ISSUE THREAD

**Issue by hariteja97** [ParikhKadam/bidaf-keras#7]
In my lubuntu 18.04 system, the code is throwing errors when I try to train the model in CLI. and I have got the error as like this.

ERROR:
Traceback (most recent call last):
  File "/home/hariteja/anaconda3/lib/python3.7/runpy.py", line 185, in _run_module_as_main
    return _run_code(code, main_globals, None,"__main__", mod_spec)
  File "/home/hariteja/anaconda3/lib/python3.7/runpy.py", line 79, in _run_code
    exec(code, run_globals)
  File "/home/hariteja/Desktop/MachineComp/bidaf/__main__.py", line 123, in <module>
    main()
  File "/home/hariteja/Desktop/MachineComp/bidaf/__main__.py", line 81, in main
    encoder_dropout=args.encoder_dropout, decoder_dropout=args.decoder_dropout)
  File "/home/hariteja/Desktop/MachineComp/bidaf/models/bidaf.py", line 37, in __init__
    similarity_matrix = Similarity(name='similarity_layer')([encoded_passage, encoded_question])
  File "/home/hariteja/anaconda3/lib/python3.7/site-packages/keras/engine/base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/hariteja/Desktop/MachineComp/bidaf/layers/similarity_layer.py", line 35, in call
    context_dim_repeat = K.concatenate([[1, 1], [num_query_words], [1]], 0)
  File "/home/hariteja/anaconda3/lib/python3.7/site-packages/keras/backend/theano_backend.py", line 892, in concatenate
    if py_all([is_sparse(x) for x in tensors]):
  File "/home/hariteja/anaconda3/lib/python3.7/site-packages/keras/backend/theano_backend.py", line 892, in <listcomp>
    if py_all([is_sparse(x) for x in tensors]):
  File "/home/hariteja/anaconda3/lib/python3.7/site-packages/keras/backend/theano_backend.py", line 93, in is_sparse
    return th_sparse_module and isinstance(tensor.type, th_sparse_module.SparseType)
AttributeError: 'list' object has no attribute 'type'

i tried everything for solving this issue and I have followed every steps like models in the saved_items and data  and everything but still couldn't solve this issue.

Any help would be great.

**Comment by hariteja97** [comment]
Please @parikhkadam  kindly help me in this issue for execution

**Comment by ParikhKadam** [comment]
@hariteja97 I already saw this issue but the problem is, we don't have a machine to test it. You may read our README.md where we are asking for donations to buy a new setup.

Thank you..

**Comment by hariteja97** [comment]
@parikhkadam ok sir thanks a lot.. when I am running in any other windows
system. I'm getting warning s like

1. Use rate instead of keep_prod..but when I executed in my system there
were no errors..

2.  I was getting the error as tf. Session error in tensorflow backend when
I run the same code in other machines

Kindly help me

**Comment by ParikhKadam** [comment]
@hariteja97 You can ignore warnings.. It won't effect the training. If there are any errors which makes a system exit, then post the full error trace here. You should open a new issue for new errors.

Thank you..

**Comment by hariteja97** [comment]
Thanks
